# Parameters and Arguments
# A parameter is a variable listed inside the function definition. An argument
# is the actual value you pass when calling the function. Parameters make
# functions flexible - the same function can work with different data every time.

def greet (name) :
 print(f"Hello, {name} !")

greet("Rahul")
greet("Priya")

# name is the parameter

# "Rahul" is the argument
# "Priya" is the argument

